joint_state_controller: 
    type: joint_state_controller/JointStateController
    publish_rate: 100

gripper_1a_position_controller:
    type: effort_controllers/JointPositionController
    joint: gripper_1a_joint
    pid: {p: 100.0, i: 0.01, d: 0.0}

gripper_1b_position_controller:
    type: effort_controllers/JointPositionController
    joint: gripper_1b_joint
    pid: {p: 100.0, i: 0.01, d: 0.0}

gripper_2a_position_controller:
    type: effort_controllers/JointPositionController
    joint: gripper_2a_joint
    pid: {p: 100.0, i: 0.01, d: 0.0}

gripper_2b_position_controller:
    type: effort_controllers/JointPositionController
    joint: gripper_2b_joint
    pid: {p: 100.0, i: 0.01, d: 0.0}

gripper_3a_position_controller:
    type: effort_controllers/JointPositionController
    joint: gripper_3a_joint
    pid: {p: 100.0, i: 0.01, d: 0.0}

gripper_3b_position_controller:
    type: effort_controllers/JointPositionController
    joint: gripper_3b_joint
    pid: {p: 100.0, i: 0.01, d: 0.0}

gripper_4a_position_controller:
    type: effort_controllers/JointPositionController
    joint: gripper_4a_joint
    pid: {p: 100.0, i: 0.01, d: 0.0}

gripper_4b_position_controller:
    type: effort_controllers/JointPositionController
    joint: gripper_4b_joint
    pid: {p: 100.0, i: 0.01, d: 0.0}
